# numpy 3

In [36]:
import numpy as np
x = [20,3,2,4,10,5,4,1,7]
y = np.array(x)
print(x)

[20, 3, 2, 4, 10, 5, 4, 1, 7]


In [17]:
# np.sort(y)[::-1]

In [49]:
x = [20,3,2,4,10,5,4,-1,7,111]
def sort_asc(x):
    for i in range(len(x)):
        m=0
        for _ in range(len(x)):
            if x[m] > x[i]:
                x[m], x[i] = x[i], x[m]
            m+=1
    print(x)

def sort_desc(x):
    for i in range(len(x)):
        m=0
        for _ in range(len(x)):
            if x[m] < x[i]:
                x[m], x[i] = x[i], x[m]
            m+=1
    print(x)

sort_asc(x)
sort_desc(x)

[1, 2, 3]
[3, 2, 1]


In [47]:
#cara mas lintang
x = [20,3,2,4,10,5,4,-1,7,111]
sortir =[]
i=0
minX=x[0]
while len(x) > 0:
    if x[i] < minX:
        minX=x[i]
    i+=1
    if i == len(x):
        sortir.append(minX)
        x.remove(minX)
        if x:
            minX=x[0]
        i=0
print(sortir)

[-1, 2, 3, 4, 4, 5, 7, 10, 20, 111]


In [53]:
z=np.array([
    [10,8,11],
    [9,4,7]
])
print(np.sort(z))
print(np.sort(z, axis=0))
# print(z)

[[ 8 10 11]
 [ 4  7  9]]
[[ 9  4  7]
 [10  8 11]]


In [70]:
x=np.arange(10).reshape(5,-1)
print(x)
print("")
print(x[:,[1,0]])
print("")
print(x[:,[0,0]])
print("")
print(np.swapaxes(x,0,1))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

[[1 0]
 [3 2]
 [5 4]
 [7 6]
 [9 8]]

[[0 0]
 [2 2]
 [4 4]
 [6 6]
 [8 8]]

[[0 2 4 6 8]
 [1 3 5 7 9]]


In [79]:
print(np.random.seed(42))
print(np.random.randn(100))
print(np.linspace(-5,5,20))

None
[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337 -0.23413696
  1.57921282  0.76743473 -0.46947439  0.54256004 -0.46341769 -0.46572975
  0.24196227 -1.91328024 -1.72491783 -0.56228753 -1.01283112  0.31424733
 -0.90802408 -1.4123037   1.46564877 -0.2257763   0.0675282  -1.42474819
 -0.54438272  0.11092259 -1.15099358  0.37569802 -0.60063869 -0.29169375
 -0.60170661  1.85227818 -0.01349722 -1.05771093  0.82254491 -1.22084365
  0.2088636  -1.95967012 -1.32818605  0.19686124  0.73846658  0.17136828
 -0.11564828 -0.3011037  -1.47852199 -0.71984421 -0.46063877  1.05712223
  0.34361829 -1.76304016  0.32408397 -0.38508228 -0.676922    0.61167629
  1.03099952  0.93128012 -0.83921752 -0.30921238  0.33126343  0.97554513
 -0.47917424 -0.18565898 -1.10633497 -1.19620662  0.81252582  1.35624003
 -0.07201012  1.0035329   0.36163603 -0.64511975  0.36139561  1.53803657
 -0.03582604  1.56464366 -2.6197451   0.8219025   0.08704707 -0.29900735
  0.09176078 -1.98756891 -0.21967189  0.357112

In [78]:
y = np.arange(10).reshape((5,-1))
print(y)
print(y.transpose())

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 2 4 6 8]
 [1 3 5 7 9]]


In [101]:
c=np.array([[1,2,3,4,5,6]])
print(c[1:,np.newaxis,:2])

[]


In [183]:
#load dari CSV file, tulis ke CSV lain

import numpy as np
id, usia=np.loadtxt('misc/0.csv', delimiter=',', skiprows=1, dtype='int32', unpack=True)
# usia=usia.reshape(-1,1)
# id=id.reshape(-1,1)

print(id)
print(usia)
# id=np.vstack(usia)
# print(id)
data=np.vstack((id,usia)).transpose()
print(data)
# np.savetxt('misc/1.csv', (id,usia), fmt='%d', delimiter=',',header='id,usia')
np.savetxt('misc/1.csv', data , fmt='%d', header='id,usia', delimiter=',', comments='')

[1 2 3 4 5 6 7 8]
[20 21 22 23 24 25 26 27]
[[ 1 20]
 [ 2 21]
 [ 3 22]
 [ 4 23]
 [ 5 24]
 [ 6 25]
 [ 7 26]
 [ 8 27]]


In [134]:
print(np.__version__)
z=np.array([0,1,2,3,4,5,6,7,8,9])
print(z)
x = np.ones((3,3), dtype='bool')
y = np.full((3,3), True, dtype='bool')
print(x)
print(y)
# arr2=z[z % 2 != 0]
# print(arr2)
# z[z % 2 != 0] = -1
# print(z)

out=np.where(z % 2 != 0, -1, z)
print(out)
print(z)
q7=np.arange(10)
q7=q7.reshape(2,-1)
print(q7)
print("")
print("#Q8")
q8a=np.arange(10).reshape(2,-1)
q8b=np.repeat(1,10).reshape(2,-1)
q8b

1.16.5
[0 1 2 3 4 5 6 7 8 9]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]

#Q8


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])