# Belajar Numpy

In [3]:
import numpy as np

In [4]:
x=[1,2,3]
x=np.array(x)
x

array([1, 2, 3])

#### array 2d

In [5]:
y=[
    [1,2,3],
    [4,5,6]
]
y=np.array(y)
y

array([[1, 2, 3],
       [4, 5, 6]])

#### array 3d

In [6]:
z = [[
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]
]]
z=np.array(z)
z

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

#### cek dimensi dan size

In [8]:
print("dimensi")
print("x:", x.ndim, "y:", y.ndim, "z:", z.ndim)

print("size")
print("x:", x.size, "y:", y.size, "z:", z.size)

print("ukuran matrix")
print("x:", x.shape, "y:", y.shape, "z:", z.shape)

dimensi
x: 1 y: 2 z: 3
size
x: 3 y: 6 z: 15
ukuran matrix
x: (3,) y: (2, 3) z: (1, 3, 5)


#### create random array

print(np.random.random(10))
print(np.random.rand(2,4))
print(np.random.randint(7, size=(2,5)))

#### numpy array slicing

In [40]:
a=[
    (1,2,3),
    (4,5,6),
    (7,8,9)
]
a=np.array(a)

# print(a[0][1])
# print(a[0,1])
# print(a[0:2, 0:2])
# print(a[0:, 0:2])
# print(a[::][1:3])
print(a[0:, 0:2])
# print(a[0:3, 0:1]) -> sintax ini buat slicing per-array
print(a[0:3, 0:1])
# print(a[0:3, 0]) -> sintax ini buat slicing per-element
print(a[0:3, 0])

[[1 2]
 [4 5]
 [7 8]]
[[1]
 [4]
 [7]]
[1 4 7]


#### more on indexing

In [101]:
a=[
    (1,2,3,10),
    (4,5,6,11),
    (7,8,9,12),
    [13,14,15,16]
]
a=np.array(a)
print(a)
print("")
a[0:3, 1]

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]
 [13 14 15 16]]



array([2, 5, 8])

#### reshape

In [91]:
print(a[0:, :1])
print(a[0:, :1].reshape(4,))
print(a[0:, :1].reshape(2,2))
print(a[0:, :1].reshape(1,4))
k=a[0:, :1].reshape(4,1,1)
print(k)

[[ 1]
 [ 4]
 [ 7]
 [13]]
[ 1  4  7 13]
[[ 1  4]
 [ 7 13]]
[[ 1  4  7 13]]
[[[ 1]]

 [[ 4]]

 [[ 7]]

 [[13]]]


#### math operation

In [122]:
b=[[0, -7],
   [-1, 3]]
c=[[2,4],
   [3,8]]
b=np.array(b)
c=np.array(c)

print(b+c)
print("========")
print(b-c)
print("========")
print(b*c)
print("========")
print(b/c)
print("========")
print(b%c)
print("========")
print(b+3)
print("========")
b[0] +=2 # nambahin cuma di elemen pertama aja
print(b)
print("========")
print(b.dot(c))

[[ 2 -3]
 [ 2 11]]
[[ -2 -11]
 [ -4  -5]]
[[  0 -28]
 [ -3  24]]
[[ 0.         -1.75      ]
 [-0.33333333  0.375     ]]
[[0 1]
 [2 3]]
[[ 3 -4]
 [ 2  6]]
[[ 2 -5]
 [-1  3]]
[[-11 -32]
 [  7  20]]


### contoh

In [121]:
#persamaan tiga dimensi asal-asalan

persamaan=[[2,1,4],
          [1,1,10],
          [3,4,5]]
# hasil=[5,7,9] # satu dimensi
hasil=[[5],[7],[9]] #dua dimensi juga bisa
persamaan=np.array(persamaan)
hasil=np.array(hasil)
# print(persamaan.shape)
# print(hasil.shape)
hasil2=np.linalg.solve(persamaan,hasil)
print(hasil2)

(3, 3)
(3, 1)
[[1.07317073]
 [0.80487805]
 [0.51219512]]


In [139]:
#SPLDV
#4x + 7y = 2
#3x + 2y = -5

matrix=[[4,7],
       [3,2]]
matrix_hasil=[2,-5]
matrix=np.array(matrix)
matrix_hasil=np.array(matrix_hasil)
hasil=np.linalg.solve(matrix, matrix_hasil)
hasil=hasil.astype('int32')
print(hasil)
x=hasil[0]
y=hasil[1]
# print(x, y)
print(2*x - 3*y)

[-3  2]
-12


In [140]:
#soal ayam dan kambing
#ayam + kambing =25
#2*ayam + 4*kambing=70

matrix=np.array([[1,1],[2,4]])
hasil=np.array([25,70])
solve=np.linalg.solve(matrix,hasil)

print(solve)


[15. 10.]


In [156]:
#soal buku pensi dan penghapus
#2b + p + h = 4700
#b + 2p + h = 4300
#3b + 2p + h = 7100

matrix=np.array([[2,1,1],
                [1,2,1],
                 [3,2,1]])
hasil=np.array([4700,4300,7100])
solve=np.linalg.solve(matrix,hasil)

print(solve)
print(f'''
buku: {(solve[0])}
pensil: {int(round(solve[1]))}
penghapus: {round(solve[2])}''')

[1400. 1000.  900.]

buku: 1400.0
pensil: 1000
penghapus: 900.0


### other properties

In [167]:
from functools import reduce

def maks(list_x):
    maks=list_x[0]
    for i in list_x:
        if i > maks:
            maks = i
    print("maximum value:", maks)
    
def mins(list_x):
    mins = list_x[0]
    for i in list_x:
        if i < mins:
            mins = i
    print("minimum value:", mins)
    
def sums(list_x):
    sums=0
    for i in list_x:
        sums+=i
    print("summary value:", sums)
    
#cara cepet
def xmax(list_x):
    xmax=reduce(lambda a,b: a if (a>b) else b, list_x)
    print("maximum value:",xmax)
    
def xmin(list_x):
    xmin=reduce(lambda a,b: a if (a<b) else b, list_x)
    print("minimum value:",xmin)
    
def xsum(list_x):
    xsum=reduce(lambda a,b: a + b, list_x)
    print("summary value:",xsum)
    

list_x=[1,2,3,4,5,6]
x = np.array(list_x)

# print(max(list_x))
# print(min(list_x))

print("From NumPy lib")
print(x.max())
print(x.min())
print(x.sum())
print("")
print("from manual function")
maks(list_x)
mins(list_x)
sums(list_x)
print("")
print("cara cepat")
xmax(list_x)
xmin(list_x)
xsum(list_x)

From NumPy lib
6
1
21

from manual function
maximum value: 6
minimum value: 1
summary value: 21

cara cepat
maximum value: 6
minimum value: 1
summary value: 21


#### statistics

In [171]:
y = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,10])
print(np.mean(y))
print(np.median(y))
print(np.mode(y))
print(np.pi)

8.125
8.5


AttributeError: module 'numpy' has no attribute 'mode'