# Belajar Pandas

In [1]:
#numpy = array, dimensi, shape
#pandas = dataframe

import numpy as np
import pandas as pd


x = np.array([1,2,3,4,5,6,7,8,9])
list=[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
x1=np.array(list)
print(x1)
xs = pd.Series(x)
xdf=pd.DataFrame(x1, index=[1,2,3],columns=['satu', 'dua', 'tiga'])
xdf['satu']

print(xs)
xs[0]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int32


1

In [2]:
x=np.random.randint(10, size=(100,50))

pdf=pd.DataFrame(x)
pdf[0]

0     8
1     2
2     6
3     3
4     2
     ..
95    7
96    6
97    8
98    9
99    6
Name: 0, Length: 100, dtype: int32

In [3]:
data=[
    {"nama":"Andi", "kota": "Jakarta"},
    {"nama":"Budi", "kota": "Bandung"},
    {"nama":"Caca", "kota": "Surabaya", "Job": np.nan},
    {"nama":"Doni", "kota": "Semarang","Job":"PNS"},

]
pdf=pd.DataFrame(data)
pdf

nama      kota  Job
0  Andi   Jakarta  NaN
1  Budi   Bandung  NaN
2  Caca  Surabaya  NaN
3  Doni  Semarang  PNS

In [4]:
x=[1,2,3,4,5]
k=pd.Series(x)
k
pdf=pd.DataFrame(k)
pdf

0
0  1
1  2
2  3
3  4
4  5

In [5]:
x=[1,2,3,4,5]
y=[6,7,8,9,10]
print(x,y)
x='farid'
print(tuple(x))

[1, 2, 3, 4, 5] [6, 7, 8, 9, 10]
('f', 'a', 'r', 'i', 'd')


In [6]:
df=pd.DataFrame({
    "A": np.arange(20,26),
    "B": [10,11,12,13,14,15],
    "C": np.random.randint(10, size=6),
    'D': np.ones(6)
})
print(df)
print(df.columns)
print(df.index)
df.describe()

A   B  C    D
0  20  10  0  1.0
1  21  11  1  1.0
2  22  12  4  1.0
3  23  13  2  1.0
4  24  14  0  1.0
5  25  15  9  1.0
Index(['A', 'B', 'C', 'D'], dtype='object')
RangeIndex(start=0, stop=6, step=1)


A          B         C    D
count   6.000000   6.000000  6.000000  6.0
mean   22.500000  12.500000  2.666667  1.0
std     1.870829   1.870829  3.444803  0.0
min    20.000000  10.000000  0.000000  1.0
25%    21.250000  11.250000  0.250000  1.0
50%    22.500000  12.500000  1.500000  1.0
75%    23.750000  13.750000  3.500000  1.0
max    25.000000  15.000000  9.000000  1.0

In [9]:
df=pd.DataFrame({
    "Aa": np.arange(20,26),
    "Bb": [10,11,12,13,14,15],
    "Cc": np.random.randint(10, size=6),
    "Fg": df["Cc"]/100,
    'GG': np.random.rand(6),
    'Dd': np.ones(6)
})
print(df)
df.iloc[:3,1:] #-> numpy-like selection and indexing

Aa  Bb  Cc    Fg        GG   Dd
0  20  10   9  0.07  0.971377  1.0
1  21  11   1  0.06  0.917272  1.0
2  22  12   3  0.00  0.355001  1.0
3  23  13   2  0.01  0.696162  1.0
4  24  14   7  0.07  0.340066  1.0
5  25  15   9  0.09  0.679353  1.0


Bb  Cc    Fg        GG   Dd
0  10   9  0.07  0.971377  1.0
1  11   1  0.06  0.917272  1.0
2  12   3  0.00  0.355001  1.0

In [14]:
df.sort_values(by='Cc',ascending=True)

Aa  Bb  Cc    Fg        GG   Dd
1  21  11   1  0.06  0.917272  1.0
3  23  13   2  0.01  0.696162  1.0
2  22  12   3  0.00  0.355001  1.0
4  24  14   7  0.07  0.340066  1.0
0  20  10   9  0.07  0.971377  1.0
5  25  15   9  0.09  0.679353  1.0

In [19]:
df.iloc[::2,0:3].sort_values(by='Aa', ascending=True)[['Bb','Cc']]

Bb  Cc
0  10   9
2  12   3
4  14   7